config/routes.rb
Socialst::Application.routes.draw do
  
  resources :countries do
  resources :statistics
  end

  resources :countries do
    resources :categories
  end

end

app/models/category.rb
class Category
  include Mongoid::Document
  field :name, type: String
  
  embedded_in :country, inverse_of: :categories
end

app/models/country.rb
class Country
  include Mongoid::Document
  field :name, type: String
  field :rank, type: Integer
  field :score, type: BigDecimal
  field :facts, type: String 
  
  validates_presence_of :name
  
  embeds_many :categories
  embeds_many :statistics
  
  
end

app/models/statistic.rb
class Statistic
  include Mongoid::Document
  field :youth_unemployment, type: BigDecimal
  field :property_rights, type: BigDecimal
  field :fiscal_freedom, type: BigDecimal
  field :monetary_freedom, type: BigDecimal
  field :freedom_from_corruption, type: BigDecimal
  
  embedded_in :country, inverse_of: :statistics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :load_country
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = @country.categories
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category =  @country.categories.build
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = @country.categories.build(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to [@country, @category], notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to [@country, @category], notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to country_categories_url(@country) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = @country.categories.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
  
  def load_country
    @country = Country.find(params[:country_id])
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render action: 'show', status: :created, location: @country }
      else
        format.html { render action: 'new' }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update_attributes(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name, :rank, :score, :facts)
    end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  before_action :load_country
  before_action :set_statistic, only: [:show, :edit, :update, :destroy]

  # GET /statistics
  # GET /statistics.json
  def index
    @statistics = @country.statistics
  end

  # GET /statistics/1
  # GET /statistics/1.json
  def show
  end

  # GET /statistics/new
  def new
    @statistic = @country.statistics.build
  end

  # GET /statistics/1/edit
  def edit
  end

  # POST /statistics
  # POST /statistics.json
  def create
    @statistic = @country.statistics.build(statistic_params)

    respond_to do |format|
      if @statistic.save
        format.html { redirect_to [@country, @statistic], notice: 'Statistic was successfully created.' }
        format.json { render action: 'show', status: :created, location: @statistic }
      else
        format.html { render action: 'new' }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statistics/1
  # PATCH/PUT /statistics/1.json
  def update
    respond_to do |format|
      if @statistic.update_attributes(statistic_params)
        format.html { redirect_to [@country, @statistic], notice: 'Statistic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statistics/1
  # DELETE /statistics/1.json
  def destroy
    @statistic.destroy
    respond_to do |format|
      format.html { redirect_to country_statistics_url(@country) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_statistic
      @statistic = @country.statistics.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def statistic_params
      params.require(:statistic).permit(:youth_unemployment, :property_rights, :fiscal_freedom, :monetary_freedom, :freedom_from_corruption)
    end
  def load_country
    @country = Country.find(params[:country_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/categories/_form.html.erb
<%= form_for([@country, @category]) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', country_category_path(@country, @category) %> |
<%= link_to 'Back', country_categories_path(@country) %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', country_category_path(@country, category) %></td>
        <td><%= link_to 'Edit', edit_country_category_path(@country, category) %></td>
        <td><%= link_to 'Destroy', [@country, category], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_country_category_path(@country) %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', country_categories_path(@country) %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_country_category_path(@country, @category) %> |
<%= link_to 'Back', country_categories_path(@country) %>

app/views/countries/_form.html.erb
<%= form_for(@country) do |f| %>
  <% if @country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% @country.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rank %><br>
    <%= f.number_field :rank %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.text_field :score %>
  </div>
  <div class="field">
    <%= f.label :facts %><br>
    <%= f.text_area :facts %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing country</h1>

<%= render 'form' %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<h1>Listing countries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rank</th>
      <th>Score</th>
      <th>Facts</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.name %></td>
        <td><%= country.rank %></td>
        <td><%= country.score %></td>
        <td><%= country.facts %></td>
        <td><%= link_to 'Show', country %></td>
        <td><%= link_to 'Edit', edit_country_path(country) %></td>
        <td><%= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Country', new_country_path %>

app/views/countries/new.html.erb
<h1>New country</h1>

<%= render 'form' %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @country.name %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @country.rank %>
</p>

<p>
  <strong>Score:</strong>
  <%= @country.score %>
</p>

<p>
  <strong>Facts:</strong>
  <%= @country.facts %>
</p>

<%= link_to 'Edit', edit_country_path(@country) %> |
<%= link_to 'Back', countries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Socialst</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/statistics/_form.html.erb
<%= form_for([@country, @statistic]) do |f| %>
  <% if @statistic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@statistic.errors.count, "error") %> prohibited this statistic from being saved:</h2>

      <ul>
      <% @statistic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :youth_unemployment %><br>
    <%= f.text_field :youth_unemployment %>
  </div>
  <div class="field">
    <%= f.label :property_rights %><br>
    <%= f.text_field :property_rights %>
  </div>
  <div class="field">
    <%= f.label :fiscal_freedom %><br>
    <%= f.text_field :fiscal_freedom %>
  </div>
  <div class="field">
    <%= f.label :monetary_freedom %><br>
    <%= f.text_field :monetary_freedom %>
  </div>
  <div class="field">
    <%= f.label :freedom_from_corruption %><br>
    <%= f.text_field :freedom_from_corruption %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statistics/edit.html.erb
<h1>Editing statistic</h1>

<%= render 'form' %>

<%= link_to 'Show', country_statistic_path(@country, @statistic) %> |
<%= link_to 'Back', country_statistics_path(@country) %>

app/views/statistics/index.html.erb
<h1><%= @country.name %></h1>
<h2>Overall Score <%= @country.score %></h2>
<table>
  <thead>
    <tr>
      <div>Rule of Law
      <th>Youth unemployment</th>
        <th>Property rights</th>
      </div>
      <th>Fiscal freedom</th>
      <th>Monetary freedom</th>
      <th>Freedom from corruption</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @statistics.each do |statistic| %>
      <tr>
        <td><%= statistic.youth_unemployment %></td>
        <td><%= statistic.property_rights %></td>
        <td><%= statistic.fiscal_freedom %></td>
        <td><%= statistic.monetary_freedom %></td>
        <td><%= statistic.freedom_from_corruption %></td>
        <td><%= link_to 'Show', country_statistic_path(@country, statistic) %></td>
        <td><%= link_to 'Edit', edit_country_statistic_path(@country, statistic) %></td>
        <td><%= link_to 'Destroy', [@country, statistic], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Statistic', new_country_statistic_path(@country) %>

app/views/statistics/new.html.erb
<h1>New statistic</h1>

<%= render 'form' %>

<%= link_to 'Back', country_statistics_path(@country) %>

app/views/statistics/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @country.name %></h1>
<h4><strong>OVERALL SCORE <%= @country.score %></strong></h4>
<h4><strong>RANK <%= @country.rank %></strong></h4>

<div>
  <h3>RULE OF LAW</h3>
<p>
  <strong>Youth unemployment:</strong>
  <%= @statistic.youth_unemployment %>
</p>

<p>
  <strong>Property rights:</strong>
  <%= @statistic.property_rights %>
</p>
</div>
<div>
<h3> LIMITED GOVERNMENT</h3>
<p>
  <strong>Fiscal freedom:</strong>
  <%= @statistic.fiscal_freedom %>
</p>

<p>
  <strong>Monetary freedom:</strong>
  <%= @statistic.monetary_freedom %>
</p>

<p>
  <strong>Freedom from corruption:</strong>
  <%= @statistic.freedom_from_corruption %>
</p>

<%= link_to 'Edit', edit_country_statistic_path(@country, @statistic) %> |
<%= link_to 'Back', country_statistics_path(@country) %>